spring:
  application:
    name: student-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps: 5
        waitDuration: 3s

      intervalFunctionExponentialExample:
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        maxRetryAttempts: 6
        waitDuration: 2s

      intervalFunctionRandomExample:
        enableRandomizedWait: true
        maxRetryAttempts: 3
        randomizedWaitFactor: 0.5
        waitDuration: 2s

      loggedRetryExample:
        maxRetryAttempts: 3
        waitDuration: 2s