spring:
  application:
    name: student-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps: 5
        waitDuration: 3s